# Generated by Django 4.2.11 on 2024-03-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_applicationrequest_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrequest",
            name="gender",
            field=models.CharField(
                choices=[("Male", "male"), ("Female", "female"), ("Others", "others")],
                default="",
                max_length=11,
            ),
        ),
    ]
