# Generated by Django 4.2.11 on 2024-03-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_applicationrequest_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrequest",
            name="category",
            field=models.CharField(
                choices=[("COMMERCIAL", "commercial"), ("RESIDENTIAL", "residential")],
                default="aadhar",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="connection_type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "individual"), ("JOINT", "joint")],
                default="individual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="district",
            field=models.CharField(
                choices=[
                    ("NORTH", "north"),
                    ("SOUTH", "south"),
                    ("EAST", "east"),
                    ("WEST", "west"),
                ],
                default="north",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female"), ("others", "others")],
                default="male",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="govt_id_number",
            field=models.CharField(default="100", max_length=16),
        ),
    ]
