# Generated by Django 4.2.11 on 2024-03-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_applicationrequest_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrequest",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("others", "Others")],
                default="male",
                max_length=11,
            ),
        ),
    ]
