# Generated by Django 4.2.11 on 2024-03-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_applicationrequest_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrequest",
            name="category",
            field=models.CharField(
                choices=[("COMMERCIAL", "Commercial"), ("RESIDENTIAL", "Residential")],
                default="Commercial",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="connection_type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "Individual"), ("JOINT", "Joint")],
                default="Individual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="district",
            field=models.CharField(
                choices=[
                    ("NORTH", "North"),
                    ("SOUTH", "South"),
                    ("EAST", "East"),
                    ("WEST", "West"),
                ],
                default="North",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("others", "Others")],
                default="Male",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="govt_id_type",
            field=models.CharField(
                choices=[("AADHAR", "Aadhar"), ("PAN", "Pan"), ("DL", "DL")],
                default="Aadhar",
                max_length=11,
            ),
        ),
    ]
