# Generated by Django 4.2.11 on 2024-03-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_applicationrequest_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrequest",
            name="gender",
            field=models.CharField(
                choices=[("male", "MALE"), ("female", "FEMALE"), ("others", "OTHERS")],
                default="Male",
                max_length=11,
            ),
        ),
    ]
