# Generated by Django 4.2.11 on 2024-03-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_applicationrequest_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrequest",
            name="category",
            field=models.CharField(
                choices=[("Commercial", "Commercial"), ("Residential", "Residential")],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="connection_type",
            field=models.CharField(
                choices=[("Individual", "Individual"), ("Joint", "Joint")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="district",
            field=models.CharField(
                choices=[
                    ("North", "North"),
                    ("South", "South"),
                    ("East", "East"),
                    ("West", "West"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Others", "Others")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="govt_id_type",
            field=models.CharField(
                choices=[("Aadhar", "Aadhar"), ("PAN", "PAN"), ("DL", "DL")],
                max_length=10,
            ),
        ),
    ]
