# Generated by Django 4.2.11 on 2024-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_applicationrequest_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrequest",
            name="application_id",
            field=models.CharField(default=342542, max_length=50),
            preserve_default=False,
        ),
    ]
