# Generated by Django 4.2.11 on 2024-03-14 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_applicationrequest_application_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrequest",
            name="date_of_application",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
