# Generated by Django 4.2.11 on 2024-03-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_applicationrequest_date_of_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviewers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=50)),
                ("reviewer_age", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="applicationrequest",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.reviewers",
            ),
        ),
    ]
