# Generated by Django 4.2.11 on 2024-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_reviewers_applicationrequest_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("In-Progress", "In-Progress"),
                    ("Completed", "Completed"),
                    ("To-Do", "To-Do"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
