# Generated by Django 4.2.11 on 2024-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_applicationrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrequest",
            name="status",
            field=models.CharField(
                choices=[("In-Progress", "In-Progress"), ("Completed", "Completed")],
                max_length=50,
            ),
        ),
    ]
