# Generated by Django 4.2.11 on 2024-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_applicationrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrequest",
            name="reviewer_comment",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("In-Progress", "In-Progress"),
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Connection Released", "Connection Released"),
                ],
                max_length=50,
            ),
        ),
    ]
