# Generated by Django 4.2.11 on 2024-03-15 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_applicationrequest_reviewer_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrequest",
            name="date_of_approval",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
