# Generated by Django 4.2.11 on 2024-03-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_applicationrequest_date_of_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrequest",
            name="date_of_approval",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
